package MeetingApp;
// Generated Apr 15, 2017 9:22:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Host generated by hbm2java
 */
public class Host  implements java.io.Serializable {


     private String hostEmail;
     private Set<Meeting> meetings = new HashSet<Meeting>(0);

    public Host() {
    }

	
    public Host(String hostEmail) {
        this.hostEmail = hostEmail;
    }
    public Host(String hostEmail, Set<Meeting> meetings) {
       this.hostEmail = hostEmail;
       this.meetings = meetings;
    }
   
    public String getHostEmail() {
        return this.hostEmail;
    }
    
    public void setHostEmail(String hostEmail) {
        this.hostEmail = hostEmail;
    }
    public Set<Meeting> getMeetings() {
        return this.meetings;
    }
    
    public void setMeetings(Set<Meeting> meetings) {
        this.meetings = meetings;
    }




}


