package MeetingApp;
// Generated Apr 15, 2017 9:22:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Part generated by hbm2java
 */
public class Part  implements java.io.Serializable {


     private String partEmail;
     private Set<PartMeeting> partMeetings = new HashSet<PartMeeting>(0);

    public Part() {
    }

	
    public Part(String partEmail) {
        this.partEmail = partEmail;
    }
    public Part(String partEmail, Set<PartMeeting> partMeetings) {
       this.partEmail = partEmail;
       this.partMeetings = partMeetings;
    }
   
    public String getPartEmail() {
        return this.partEmail;
    }
    
    public void setPartEmail(String partEmail) {
        this.partEmail = partEmail;
    }
    public Set<PartMeeting> getPartMeetings() {
        return this.partMeetings;
    }
    
    public void setPartMeetings(Set<PartMeeting> partMeetings) {
        this.partMeetings = partMeetings;
    }




}


