package MeetingApp;
// Generated Apr 15, 2017 9:22:30 PM by Hibernate Tools 4.3.1



/**
 * PartMeeting generated by hbm2java
 */
public class PartMeeting  implements java.io.Serializable {


     private Integer partMeetingId;
     private Meeting meeting;
     private Part part;
     private Status status;

    public PartMeeting() {
    }

    public PartMeeting(Meeting meeting, Part part, Status status) {
       this.meeting = meeting;
       this.part = part;
       this.status = status;
    }
   
    public Integer getPartMeetingId() {
        return this.partMeetingId;
    }
    
    public void setPartMeetingId(Integer partMeetingId) {
        this.partMeetingId = partMeetingId;
    }
    public Meeting getMeeting() {
        return this.meeting;
    }
    
    public void setMeeting(Meeting meeting) {
        this.meeting = meeting;
    }
    public Part getPart() {
        return this.part;
    }
    
    public void setPart(Part part) {
        this.part = part;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }




}


