package MeetingApp;
// Generated Apr 15, 2017 9:22:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private String statusType;
     private Set<PartMeeting> partMeetings = new HashSet<PartMeeting>(0);

    public Status() {
    }

	
    public Status(String statusType) {
        this.statusType = statusType;
    }
    public Status(String statusType, Set<PartMeeting> partMeetings) {
       this.statusType = statusType;
       this.partMeetings = partMeetings;
    }
   
    public String getStatusType() {
        return this.statusType;
    }
    
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }
    public Set<PartMeeting> getPartMeetings() {
        return this.partMeetings;
    }
    
    public void setPartMeetings(Set<PartMeeting> partMeetings) {
        this.partMeetings = partMeetings;
    }




}


